### ISSUE TITLE
crd-schema-gen should output "minimum: 0" for uint32

### ISSUE THREAD

**Issue by danwinship** [openshift/crd-schema-gen#9]
The networking config and operator types have some `uint32` fields:

    config/v1/types_network.go
    74:	HostPrefix uint32 `json:"hostPrefix"`
    
    operator/v1/types_network.go
    79:	HostPrefix uint32 `json:"hostPrefix"`
    121:	MTU uint32 `json:"mtu,omitempty"`
    213:	VXLANPort *uint32 `json:"vxlanPort,omitempty"`
    218:	MTU *uint32 `json:"mtu,omitempty"`
    234:	DaemonProbesPort *uint32 `json:"daemonProbesPort,omitempty"`
    238:	ControllerProbesPort *uint32 `json:"controllerProbesPort,omitempty"`
    247:	MTU *uint32 `json:"mtu,omitempty"`

(`kubecontrolplane/v1/types.go` also has one `uint32` field)

crd-schema-gen accepts these, but generates a schema with, eg:

                  hostPrefix:
                    description: The size (prefix) of block to allocate to each node.
                    format: int32
                    type: integer

That means that validation will accept JSON objects with negative numbers in that field, which will result in an object that can't be read into a golang object. It should add `minimum: 0`.

(I know you can use kubebuilder tags to get it to do that, but it ought to do it automatically.)

(If the answer is "you're not supposed to use `uint32` in API types, then something, somewhere, ought to be complaining loudly about that, rather than just generating an almost-but-not-quite-right CRD for it.)

**Comment by soltysh** [comment]
@sttts @damemi fyi

**Comment by damemi** [comment]
This should probably be opened against the [upstream controller-tools repo](https://github.com/kubernetes-sigs/controller-tools), but we will look into it

**Comment by sttts** [comment]
I see the issue, but I doubt automatic minimum & maximum is the answer. These limits are wrong most of the time. Clear, visible warnings would be better. But as @damemi writes, this must go to controller-tools.
